#!/bin/bash

MSVA_PORT=$RANDOM
let "MSVA_PORT %= 1000"
let "MSVA_PORT += 33000"
export MSVA_PORT
msva-perl >/dev/null&
MONKEYSPHERE_VALIDATION_AGENT_SOCKET=http://127.0.0.1:${MSVA_PORT};
export MONKEYSPHERE_VALIDATION_AGENT_SOCKET;
