# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="5"

MODULE_AUTHOR="AJUNG"

inherit perl-module

DESCRIPTION="Pure Perl X.509 Parser"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=">=dev-perl/Convert-ASN1-0.220.0
	dev-lang/perl"

RDEPEND="${DEPEND}"
